# Generated by Django 2.0 on 2017-12-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Apartament',
            name='title',
        ),
        migrations.AddField(
            model_name='Apartament',
            name='bedroom',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Apartament',
            name='diningroom',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Apartament',
            name='livingroom',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Apartament',
            name='livingroom2',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
